import React, { useState, useCallback, useEffect } from 'react';
import { ReactFlow, MiniMap, Controls, Background, useNodesState, useEdgesState, addEdge } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useAuthStore } from '../store/authStore';
import { Button } from '@/components/ui/button';
import { Loader2, Zap, Map } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const initialNodes = [
  { id: '1', position: { x: 250, y: 150 }, data: { label: 'Click Generate to Build Your Path' } }
];

export default function CareerGraph() {
  const { user } = useAuthStore();
  const token = user?.token;
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const [loading, setLoading] = useState(false);
  const [insight, setInsight] = useState('');

  const onConnect = useCallback((params: any) => setEdges((eds) => addEdge(params, eds)), [setEdges]);

  const generateGraph = async () => {
    setLoading(true);
    setInsight('');
    try {
      const res = await fetch('http://localhost:3000/api/users/career-graph/generate', {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        
        // Add styling to nodes generated by AI
        const styledNodes = data.nodes.map((node: any) => ({
          ...node,
          style: {
            background: 'hsl(var(--background))',
            color: 'hsl(var(--foreground))',
            border: '2px solid hsl(var(--primary))',
            borderRadius: '8px',
            padding: '10px 20px',
            fontWeight: 'bold',
            boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)'
          }
        }));

        const styledEdges = data.edges.map((edge: any) => ({
          ...edge,
          animated: true,
          style: { stroke: 'hsl(var(--primary))', strokeWidth: 2 }
        }));

        setNodes(styledNodes);
        setEdges(styledEdges);
        if (data.insight) setInsight(data.insight);
      }
    } catch (err) {
      console.error('Failed to generate graph', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="h-[80vh] flex flex-col space-y-4 animate-in fade-in duration-500 max-w-7xl mx-auto">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white border border-slate-200 rounded-3xl p-6 shadow-sm">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center">
            <Map className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Career Architecture Graph</h1>
            <p className="text-sm text-slate-500 font-medium">Interactive visualization of your path to mastery.</p>
          </div>
        </div>
        <Button 
          onClick={generateGraph} 
          disabled={loading}
          className="bg-primary hover:bg-primary/90 text-primary-foreground font-bold shadow-md hover:shadow-lg transition-all h-12 px-6 rounded-xl"
        >
          {loading ? <><Loader2 className="w-5 h-5 mr-2 animate-spin" /> Architecting Path...</> : <><Zap className="w-5 h-5 mr-2" /> Generate My Path</>}
        </Button>
      </div>

      <AnimatePresence>
        {insight && (
          <motion.div 
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="bg-primary/5 border border-primary/20 p-4 rounded-xl text-primary-foreground relative overflow-hidden shadow-sm"
          >
            <div className="absolute inset-0 bg-primary opacity-[0.03]"></div>
            <p className="relative z-10 text-slate-800 font-medium leading-relaxed">
              <span className="font-bold text-primary block mb-1">Mentor Insight:</span>
              {insight}
            </p>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="flex-1 w-full rounded-3xl border border-slate-200 overflow-hidden shadow-inner bg-slate-50 relative">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onConnect={onConnect}
          fitView
          attributionPosition="bottom-right"
        >
          <Controls className="bg-white border-slate-200 shadow-md rounded-xl overflow-hidden" />
          <MiniMap 
            nodeColor={(node) => 'hsl(var(--primary))'}
            maskColor="rgba(255, 255, 255, 0.8)"
            className="rounded-xl border border-slate-200 shadow-md" 
          />
          <Background color="hsl(var(--border))" gap={20} size={2} />
        </ReactFlow>
      </div>
    </div>
  );
}
